In [183]:
import numpy as np
import random
import decimal

vector = np.array([[float(random.randint(1, 10)) for _ in range(5)] for _ in range(5)])
print (vector)

def reduce(vector):
    a=0
    for i in range(len(vector)-1):
        for j in range(i+1, len(vector)):
            if vector[i][i] != 0:
                vector[j] -= vector[j][i]/vector[i][i]*vector[i]
    vector[-1] /= vector[-1][-1]
    for i in range(len(vector)-1, 0, -1):
        for j in range(i-1, -1, -1):
            if vector[i][i] != 0:
                vector[j] -= vector[j][i]/vector[i][i]*vector[i]
        if vector[i][i] != 0:
            vector[i-1] = vector[i-1] / vector[i-1][i-1]
    np.around(vector, 3)        

    
reduce(vector)

print (vector)

[[ 6.  8.  3.  2.  3.]
 [ 9.  5. 10.  6.  6.]
 [ 5.  8.  2.  9.  6.]
 [ 5.  7.  7.  8.  1.]
 [ 2.  2. 10.  5. 10.]]
[[ 1.  0.  0.  0.  0.]
 [-0.  1. -0. -0. -0.]
 [ 0.  0.  1.  0.  0.]
 [-0. -0. -0.  1. -0.]
 [ 0.  0.  0.  0.  1.]]
